### ISSUE TITLE
User can choose which columns should be shown

### ISSUE THREAD

**Issue by MTrost** [nuvla/ui#1014]
- New Table wrapper 
   - [x] Construct `available-columns` is generated from `columns` if available and `rows`, specifically: `field-key` from single `col-config` maps in `columns` and all `keys` from all documents in `rows`. `available-columns` is a map of `field-key->col-config`. `col-config` is an empty map if coming from `rows` or a full col-config if coming from `columns`.
   - [x] init db with 
     - `current-cols` -> vector of `field-keys`
     - `default-cols` -> vector of `field-keys`
   - [x] render `Table` with updated props for `columns` plus a new `col-config`
   - [x] Events to remove and add single column (at the end or specific `position`) and reset to `default-columns`
   - [x] Subscriptions to get `default-columns` and `current-columns`
   - [x] Store in local storage when changing columns
   - [x] Read from local storage when rendering table
   - [x] Make it specific for where it was rendered by passing in a `db-path`
- [x] Test it with Edges table
- [x] Make it work with `RowFn` (`render-row-fn` props of `Table`): Currently hardcoded entire row, so when you remove a column, only the column header is removed -> Removed row-render option for table
- Changes to Table component: Add UI stuff to control all of it
   - [x] remove icon on column header
   - [x] Add dropdown on hovering a column header
   - [ ] Modal to change all columns at once
- [x] Sort sorting out :(

**Comment by 0xbase12** [comment]
![Screenshot 2023-10-11 at 11 37 30](https://github.com/nuvla/ui/assets/5518233/715c1a47-28b2-4b57-a869-e8801416c316)

**Comment by 0xbase12** [comment]
Style of the button of course can be changed. Here is a simpler one.
`<Button basic icon floated='left' style={{'box-shadow': 'none', padding: 0}}>`
