### ISSUE TITLE
when ES db is not available, POST on /ui/sign-in returns HTML from nginx 

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#1035]
... which is failing to be parsed by UI and then gets displayed as an error message on the login page

![Screenshot 2022-12-06 at 16 55 50](https://user-images.githubusercontent.com/353767/205960171-c39e8b76-6dc3-496b-b923-570b7021b057.png)

The actual chatter.

![Screenshot 2022-12-06 at 16 59 53](https://user-images.githubusercontent.com/353767/205961100-71a219fd-a9e6-4dbd-a4e7-727613c331b0.png)

**Comment by konstan** [comment]
IMHO, UI client shouldn't display that raw error message from Nginx to the user. So, if something but JSON is received, it's better to say the user that the service is not available at the moment.

All UI static pages and .js are served from `ui` container which is running Nginx :) https://github.com/nuvla/ui/blob/master/container/Dockerfile with Nginx configs here https://github.com/nuvla/ui/tree/master/container/src/config

But yes - there is a follow-up issue to resolve the problem with API server and ES comm.

**Comment by MTrost** [comment]
Makes sense, thanks for the response!

**Comment by 0xbase12** [comment]
The issue come from the fact that Cloud-entry-point return 200 even with an ES error. 
Traefik health check is based on `api/cloud-entry-point` call which make that traefik consider api-server as healthy. 
UI post on session and get an error with a redirect-url pointing to the ui.

- [ ]  nuvla/api-server#742
- [ ] nuvla/deployment#75
