### ISSUE TITLE
Only show published NuvlaEdge releases

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#1053]
Require nuvla/api-server#735

Show if `published=true` or if _active-claim_ is on the ACL.
Example query filter: `published=true or published=null or acl/view-data=<group/test>`

**Comment by MTrost** [comment]
@schaubl I think we can implement this without the api-server changes, as long as we handle both cases (NuvlaEdge releases with published flag and without). If there is a NuvlaEdge with a published flag, filter and only show those with published flag, else show all returned releases.

**Comment by MTrost** [comment]
I even go a step farther: I think this should be done before the api server changes and handle both api versions, else we show all releases until we have implemented this.
