### ISSUE TITLE
404 for https://nuvla.io/terms/app-license from “Nuvla.io Apps 1.0”

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#1067]
404 for https://nuvla.io/terms/app-license

![Screenshot 2022-12-21 at 15 26 36](https://user-images.githubusercontent.com/353767/208928695-ab01e8ee-8e2c-4c91-a49f-ca5391973173.png)

from “Nuvla.io Apps 1.0”

![Screenshot 2022-12-21 at 15 26 46](https://user-images.githubusercontent.com/353767/208928703-b4f73385-df40-4552-907f-0d60aaaca69f.png)

**Comment by mebster** [comment]
Should be: https://sixsq.com/legal/generic-apps-license.html
