### ISSUE TITLE
more than one component with the same name in a project module, but UI always opens the first created one

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#108]
It's possible to have more than one component with the same name in a project module, but UI opens always the first created one. It's not possible to open the second one.

![Screenshot 2019-05-29 at 12 00 45](https://user-images.githubusercontent.com/353767/58548576-df0d0600-8209-11e9-9569-8b188b594e4d.png)

**Comment by mebster** [comment]
Perhaps a simple first step would be to forbid path/name duplicates in all modules.

**Comment by 0xbase12** [comment]
I think the best way to get unique path.

Name and description are common attributes for all resources and their usage should stay the same and coherent between resources, this is why I don't like the idea to make name unique.

To verify that path is unique on server, we derive uuid from the path. This will require to reindex 17 existing modules in production to get the new uuids.

**Comment by 0xbase12** [comment]
@mebster pointed the issue of moving module to another path. 
This give advantage to make a search in modules to check if the path is unique without using the dervied uuids.

For info: In the UI, actually the name field is used to specify the name and the path of the module at the same time. The path is created from the name but is lowercase string with spaces replaced by dash
