### ISSUE TITLE
clicking on Dashboard disables auto refresh and removes refresh counter but leaves 's'

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#1124]
Before clicking on the Dashboard button (at the top)

<img width="450" alt="Screenshot 2023-01-29 at 23 14 48" src="https://user-images.githubusercontent.com/353767/215358670-dd3c8b0e-80e8-4072-bdca-7be737e53d7a.png">

After clicking on Dashboard

<img width="457" alt="Screenshot 2023-01-29 at 23 14 55" src="https://user-images.githubusercontent.com/353767/215358689-cd8a28f6-fd48-4009-a549-a9424927e2bc.png">

**Comment by 0xbase12** [comment]
This bug is also present in deployments page.  For sure in other pages also.
