### ISSUE TITLE
UI for not shared deployment displays Unknown resource: ["deployment" "XXX"]

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#115]
![Screenshot 2019-05-29 at 13 45 15](https://user-images.githubusercontent.com/353767/58554990-b0e2f280-8218-11e9-84e1-0f8106669baf.png)

**Comment by konstan** [comment]
Invalid.

**Comment by konstan** [comment]
Reopening as the problem is really there. I tried to access a deployment deployed by someone else.

**Comment by 0xbase12** [comment]
Replace deployment by dashboard in you url and it will work.

I want to keep navigation as logic as possible, so when you click on dashboard in sidebar, you go to dashboard page and url is /dashboard. 
Before it was  when you click dashboard in sidebar, you go to /deployment in url

**Comment by konstan** [comment]
It redirects me to /dashboard with an error message.

<img width="1680" alt="Screenshot 2019-05-29 at 16 13 56" src="https://user-images.githubusercontent.com/353767/58564208-d37f0680-822c-11e9-934d-cba96b59ac53.png">

However, initially this was the link that was posted by @schaubl on Slack. I don't know how he obtained it (@schaubl ???) but I believe he copied it from the browser.

**Comment by konstan** [comment]
<img width="781" alt="Screenshot 2019-05-29 at 16 07 53" src="https://user-images.githubusercontent.com/353767/58564294-f8737980-822c-11e9-8845-b190ae67cc84.png">

**Comment by konstan** [comment]
The agreement was to update the shown error message. Something along the line: "Resource doesn't exist or you don't have access to it".
