### ISSUE TITLE
Ignore changes modal should not allow navigation through browser navigation buttons while it's open

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/ui#1155]
Way to reproduce:

- Open browser and sign in
- Navigate to "Apps"
- Select "Navigate Apps" 
- Add a project
- Update project name
- Navigate to another page such ignore changes modal appear
- Use now browser arrow to navigate history back

Bug is that navigation is possible while modal is open and changes are lost.

**Comment by MTrost** [comment]
Additional issues when navigating backward and forward when changes protection is active (modal not yet open, but some data was edited without saving):
- the modal opens but can only be closed with button "Ignore Changes"
- and then although the "Ignore Changes" closes the modal and the navigation is performed, ignore changes isn't "saved", i.e. `changes-protection` is not set to nil and next navigation shows ignore changes modal again

**Comment by MTrost** [comment]
- Changes protection  
	- Testing:  
		- NOT IGNORING CHANGES,  
			- the navigation doesn't happen or is reverted and  
			- All protections stay in place  
				- Browser popstate event: Browser backward and forward open protection modal  
				- Browser unload event: Browser reload opens browser native confirmation modal  
				- app-db `changes-protection` true: Main menu navigation opens protection modal  
		- IGNORING CHANGES,  
			- the navigation does happen (or if it already happened, should not be reverted),  
			- All protections are cleared  
				- Browser popstate event: Browser backward and forward work again (for in app, i.e. pure client side navigation)  
				- Browser unload event: Browser reload works  
				- app-db `changes-protection` false: Main menu navigation works  
	- Cases of opening change protection modal  
		- [ ] when main navigation item was clicked (not handled by reitit ... iirc)  
			- [ ] NOT IGNORING CHANGES:  
				- [ ] click outside  
				- [ ] click X  
				- [x] browser navigate back button  
					- [x] Clear event on popstate that closes modal on navigate back  
						- [ ] Why double back needed for triggering modal again?  
			- [ ] IGNORING CHANGES  
				- [ ] Click "ignore changes"  
		- [ ] Tab navigations (not handled by reitit, so should work if main nav works)  
			- [ ] NOT IGNORING CHANGES:  
				- [ ] click outside  
				- [ ] click X  
				- [ ] browser navigate back button  
			- [ ] IGNORING CHANGES  
				- [ ] Click "ignore changes"  
		- [ ] Clicking link handled by reitit and test  
			- [ ] NOT IGNORING CHANGES:  
				- [ ] click outside  
				- [ ] click X  
				- [ ] browser navigate back button  
			- [ ] IGNORING CHANGES  
				- [ ] click outside  
				- [ ] click X  
				- [ ] browser navigate back button  
			- [ ] IGNORING CHANGES  
				- [ ] Click "ignore changes"
