### ISSUE TITLE
Delete credential broken

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/ui#1158]
How to reproduce:

1. Go to `credential` page
2. Select `Access keys` tab for example
3. Delete a credential
4. Confirm deletion in modal
5. Bug appear (Modal doesn't close) + Credentials count in navigation tab doesn't decrement because pane wasn't rerendered 

When a credential is deleted successfully, re-frame event `get-credentials` should reload credentials by a search query.
Deleted credential should not be in the list of the query, credential component is unmounted and make disappear the modal.

**Comment by MTrost** [comment]
TESTING
