### ISSUE TITLE
Docker compose file is not loaded when starting on `apps-tab=docker`

### ISSUE THREAD

**Issue by MTrost** [nuvla/ui#1171]
Bug: Docker compose file is not loaded when starting on `apps-tab=docker`

[Slack Message](https://sixsq.slack.com/archives/C029X32LN/p1676968913160369)

**Comment by 0xbase12** [comment]
Seem related to a bug in codemirror. Took the opportunity to upgrade to codemirror 6 and move to a maintained react codemirror implementation.
