### ISSUE TITLE
Notifications: display value unit in Rx/Tx notification configuration

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#1186]
Add `GiB` after the edit box and change `GB` to `GiB`.

![Screenshot 2023-03-06 at 13 09 35](https://user-images.githubusercontent.com/353767/223107685-1786dd38-369f-4649-a513-37d16700a2fc.png)

**Comment by MTrost** [comment]
Feel free to assign it to me if you want to

**Comment by konstan** [comment]
Thanks. Assigned to you.

Note: For the `Value` edit box this needs to be done conditionally - only when `Metric` starts with `network-`.
