### ISSUE TITLE
API page resource list not cleaning when changing to a different tab results in impossibility of searching when returning to API tab

### ISSUE THREAD

**Issue by ignacio-penas** [nuvla/ui#1191]
After a search on the API tab the latest searched resource is saved so when returning to the API tab the resource is shown as follows:

![Screenshot 2023-03-13 at 10 58 35](https://user-images.githubusercontent.com/11061525/224669708-834ce6b6-b466-439a-845c-249a68ce7738.png)

However, it is not possible to search for that same resource unless the page is reloaded or another resource is selected.

**Comment by MTrost** [comment]
There are some fixes for the api page in this PR: https://github.com/nuvla/ui/pull/1187

But I just checked and this is not one of them. Will look into it and decide if I make it part of the same PR (probably).

**Comment by ignacio-penas** [comment]
Ok, doesn't seem like an critical bug. Just to keep track of it.

**Comment by 0xbase12** [comment]
Checked on master branch, bug is still there. No reason to be in pending. If there is a reason please put it in a comment.
