### ISSUE TITLE
App: copy-pasting non-published an app retains the owner and Rights of the initial app

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#1192]
Below is the app that I had read-only access to and was able to copy. After pasting it, it retained the initial owner and the Rights (ACLs).

![Screenshot 2023-03-14 at 09 07 48](https://user-images.githubusercontent.com/353767/224936619-90bad4ac-ed8d-4dcb-a602-c31d2646f7ae.png)

Now after copying under My Apps space, I'm not able to edit the app 🤷🏻‍♂️ .

IMO, the following is expected if a user can copy an app:
* the new user becomes the only owner
* (before saving pasted app) ask the user if she wants to either retain Rights or empty them.

**Comment by MTrost** [comment]
Now that is a feature that could use some enhancements and explanations!

**Comment by 0xbase12** [comment]
Duplicated closing
