### ISSUE TITLE
adapt UI for adding new NE for deployment on k8s-based edge device

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#1243]
- [x] Design and implement updates to the current edge `+Add` modal to accommodate for the deployment of NE on k8s-based edge device

- [ ] The info for deployment on k8s-based edge device must contain 
  - [x] helm command for adding the Helm repo
  - [x] helm command for the deployment of the selected release
  - [ ] link to the corresponding documentation section on docs.nuvla.io (as result of [this ticket](https://github.com/nuvla/documentation/issues/108)).

**Comment by konstan** [comment]
@0xbase12 and @MTrost I assigned this to you and put it in ToDo. This still needs design.

**Comment by MTrost** [comment]
Quick mockup of the updated add modal based on our call @konstan :

1. Creation screen:

<img width="443" alt="image" src="https://github.com/nuvla/ui/assets/10104888/132a43bb-c6ff-4e91-a239-4fe28b7bed0e">

- If Docker is chosen, the current form shows and user has to choose between Compose file bundle or USB stick before she can create the Edge. 
- If Kubernetes is chosen, it is highlighted and the user can create the Edge without any additional step.

2. Success screen for k8s:
<img width="443" alt="image" src="https://github.com/nuvla/ui/assets/10104888/28473802-0dc4-41d5-8467-94452ad0c5e3">

I'll need strings for (1), (2), (3), and (4), but I can proceed without them and I ping you when I'm done. I work on it on Monday morning.

@mebster do you have any feedback or comments for this?

**Comment by konstan** [comment]
Comment regarding `Additional modules`. In the case of installation using `helm`, all the "peripheral managers" are already defined in the NE's helm chart. To enable them, helm deploy command (3) must be extended with `--set peripheralManagerGPU=true` etc (as per https://github.com/nuvlaedge/deployment/tree/main/helm#enable-optional-nuvlaedge-engine-components). If it's not a big hassle for the initial phase, I would suggest deriving the `--set` list for (3) from the list of the (un-)checked modules. Otherwise, the `Additional modules` must be hidden for now during the INSTALLATION METHOD selection, and then only shown when Docker is selected. For the case of K8s the user then will be invited to consult the documentation for managing the list of the modules.

**Comment by mebster** [comment]
> If Docker is chosen, the current form shows and user has to choose between Compose file bundle or USB stick before she can create the Edge.

Is there a reason why would the USB stick be limited to Docker?  I think it equally applies to k8s, no?

**Comment by mebster** [comment]
Regarding the additional modules, are they not only applicable to non-USB method?  I don't think we store in the NE resource these choices (perhaps we should?), such that when the "USB stick install script" runs on the NE using t, it has no memory of what additional modules were selected at creation.

**Comment by MTrost** [comment]
> Is there a reason why would the USB stick be limited to Docker? I think it equally applies to k8s, no?

I don't know! Though I would guess we we'd need more work for making USB stick work while we can already offer installation via copy-pasting helm commands. But just my guess, perhaps USB stick is not available/planned at all. @konstan ?

> Regarding the additional modules, are they not only applicable to non-USB method? I don't think we store in the NE resource these choices (perhaps we should?), such that when the "USB stick install script" runs on the NE using t, it has no memory of what additional modules were selected at creation.

This is a general question and not only applicable to this issue right?

**Comment by konstan** [comment]
> But just my guess, perhaps USB stick is not available/planned at all. @konstan ?

Late reply. This was already discussed. So, replying just for traceability. USB stick based installation (https://github.com/SixSq/tasklist/issues/2305) is planned to support NE installation on K8s as well. For now, it's only supported on Docker-based edge.

**Comment by konstan** [comment]
@MTrost this is the future link to the helm-based deployment documentation 
https://docs.nuvla.io/nuvlaedge/installation/install-with-helm/. The link is not available yet as the merge of the [documentation PR](https://github.com/nuvla/documentation/pull/110) will happen later along with the UI release which will introduce this feature.

**Comment by MTrost** [comment]
Added to the open PR

**Comment by konstan** [comment]
@MTrost thank you!
