### ISSUE TITLE
Map broken in master

### ISSUE THREAD

**Issue by MTrost** [nuvla/ui#1298]

**Comment by 0xbase12** [comment]
What is broken? 
I remember that I tested it a little bit without having any issue?

**Comment by MTrost** [comment]
App crashes when you open "Select on map" in a Data set.

But it is a bit weird, as the error messages in the console states:

```
react-leaflet-draw.js:320 Uncaught Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>
```

But `MapContainer` was only introduced in version 3 of `react-leaflet`, we use v2.8.

**Comment by MTrost** [comment]
Oh, it's `react-leaflet-draw` 💡
