### ISSUE TITLE
Change of ACL in deployment doesn't propagate to deployment parameters

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#161]

**Comment by schaubl** [comment]
It prevent to be able to "really" share a deployment.
For example the links are not working because output parameters ACL are not updated.

**Comment by schaubl** [comment]
What about ACL inheritance ?

For example if a resource has a "parent" and a flag enabled by default which enable ACL inheritance, the ACL of the parent(s) can be merged.

I think it can be a generic solution that can be applied everywhere but it will be especially useful for _Deployments_, _NuvlaBox_ and _Modules_.

**Comment by 0xbase12** [comment]
We usually need different ACLs of the parent ones. Check NuvlaBox sub-resources acls which are different depending on their type, credentials subtype, peripherals etc.

**Comment by 0xbase12** [comment]
Fixed here https://github.com/nuvla/api-server/commit/8b03f3dabf985303c76c7ad433cfc1f1f16baab0
