### ISSUE TITLE
For examples, ACL widget shows empty content

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#173]
This applies to Ubuntu, CentOS, Jupyter and RStudio.

**Comment by 0xbase12** [comment]
After check, the issue is that server is not returning acl field because the owner didn't allow view-acl.
In this case I'll hide completly the ACL button. Do you agree with this behavioe?

**Comment by mebster** [comment]
Yes.  But the examples should then be changed to allow view of the ACL.  Unless there's a reason for this to be hidden.

**Comment by 0xbase12** [comment]
Fixed 5a85287fe43548ba822c8517fd31fb737f706c7b

I didn't change ACL's on components. I'll let you (@mebster ) check with @loomis the reason why the view-acl wasn't set for examples
