### ISSUE TITLE
ACL display/edit widget doesn't show all informations

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#180]
Real example:
On the following deployment we see only the group `Nuvla Administrator Group` in the list of `owners`.
But if we look in raw (json), this group is not an owner but instead there is a user.

The deployment:
- on api page: https://nuvla.io/ui/api/deployment/84b8a30a-9d5e-4161-b323-39349871c2a0
- on dashboard page: https://nuvla.io/ui/dashboard/84b8a30a-9d5e-4161-b323-39349871c2a0

By looking at all the ACL in raw we can see that what is display on the "ACL widget" doesn't match the real ACL, not only for the `owners` field.

**Comment by 0xbase12** [comment]
I don't see the issue @schaubl. The acl is 
```
  "acl": {
    "owners": [
      "group/nuvla-admin"
    ]
  }
``` and the acl widget is showing this as well
