### ISSUE TITLE
implement 'select' check-boxes for bulk operations on resources in /ui/api

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#190]
`select + delete` would be a really great combination as cleaning up one-by-one is really tedious.

![Screenshot 2019-07-02 at 22 26 31](https://user-images.githubusercontent.com/353767/60544990-45f67100-9d1a-11e9-9d4e-8ac1423b4137.png)

I'm not talking about operations on 1K resources (this should be done with a proper cleanup scripts), but for 20-50 resources this would be very handy.

**Comment by mebster** [comment]
This should be extended to potentially all lists in the ui - e.g.: deployments. But it should be balanced with the ability to protect resources and the need to confirm destructive actions.
