### ISSUE TITLE
when creating a new resource, the UI is converting double to int

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#193]
To replicate, simply try to create a voucher resource with:

```
{
  "owner": "user/<uuid>",
  "target-audience": "some_researchers@science.org",
  "amount": 50.0,
  "currency": "EUR",
  "code": "CEODDOECXYZ01",
  "state": "NEW"
}
```

and you'll see a schema error due to `50.0` being converted to `50`.

**Comment by mebster** [comment]
With 50.1 it works. Strange.

**Comment by 0xbase12** [comment]
There is no such thing as an integer in JavaScript. Numbers in JavaScript are "double-precision 64-bit format IEEE 754 values".

Open up your web browser's console and type 1.0. You'll see 1 printed out. All numbers in JavaScript are floating point numbers, so your serializer simply chose to leave off unnecessary precision.

ref:  https://stackoverflow.com/questions/16662031/json-stringify-conversion-of-float-to-int
