### ISSUE TITLE
As Dave, owner of a NuvlaBox, I can share the NuvlaBox with other users, such that they can deploy on it

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#209]
This should propagate the necessary ACL adjustments to all required resources - e.g. nuvlabox, credential, infrastructure service.

**Comment by mebster** [comment]
As well as nuvlabox-status resource

**Comment by 0xbase12** [comment]
Fixed in this commit a8a00fd70b7a6874395942a535cda9d1442c47db
