### ISSUE TITLE
Rendering problems with long module descriptions

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#216]
Description should wrap around in view mode and possibly be a `textarea` in edit mode.

Safari:
![Screenshot 2019-07-29 at 14 36 39](https://user-images.githubusercontent.com/419519/62049114-d8513e00-b20e-11e9-85f1-b27635655dbd.png)

Chrome:
![Screenshot 2019-07-29 at 14 36 25](https://user-images.githubusercontent.com/419519/62049115-d8513e00-b20e-11e9-98ab-ccd1c64cba06.png)

**Comment by 0xbase12** [comment]
Fixed in this commit fb3517b
