### ISSUE TITLE
Simplify Display name of NuvlaBoxes

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#239]
![Screenshot 2019-10-04 at 13 47 38](https://user-images.githubusercontent.com/419519/66205421-a8f6fb80-e6ad-11e9-9ef0-9b7605003159.png)

The last item in the list should simply say: "Meb's NuvlaBox Nano", with the description in the second line. UUIDs should only be used if name and description are not present

**Comment by 0xbase12** [comment]
Name and description of nuvlabox, infra-swarm, infra-minio, cred, swarm-token are defined by api-server at creation time. So naming changes will be visible only for newly created NuvlaBox
