### ISSUE TITLE
on the edge page, allow filtering by label/tag

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#306]

**Comment by mebster** [comment]
It is possible with the search input field. Close?

**Comment by mebster** [comment]
I think this is done. @cjdcordeiro can you confirm?

**Comment by cjdcordeiro** [comment]
yes. However filtering by key=value doesn't work (the "=" seems to break the search). Is that intentional? If not, let's then close this ticket and open a separate one with the bug report

**Comment by mebster** [comment]
Yes let's do that.  There are a few characters that are not supported, including the "=" sign.
