### ISSUE TITLE
Allow users to create SSH keys and assign these to a NuvlaBox

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#310]
Nuvla should only keep the public key and allow the user to save the private key (with the note that this is the only opportunity to save the key, since Nuvla will not keep it).
When registering a new NuvlaBox, the public key should be (as an option?) configured for SSH connection, while ensuing that password SSH connection is disabled.

**Comment by cjdcordeiro** [comment]
@mebster this is now covered right?

**Comment by mebster** [comment]
Yes. Closing.
