### ISSUE TITLE
Data page queries against data-record resource download MBs from the server

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#325]
This is because the current query uses `select=id`. With millions of objects (GNSS) this results in MBs in traffic and slow updates in the cards. But in the end the IDs are not used. Actually the cards only use aggregations `value_count:id` and `sum:bytes`. 

Solution: add `last=0` to the query.

**Comment by 0xbase12** [comment]
After check. There is following query in the Data page:
```
aggregation: value_count:id, sum:bytes
filter: ((timestamp>='2020-01-31T23:00:00Z' and timestamp<'2020-03-01T23:00:00Z')) and (content-type='gnss/ion')
select: id```

The aggregation output is used to display data-record stats by data-set in the data page. 
The data records ids fetched within this query are used in the deployment modal to associate them to the Deployment resource to allow him to know which data to fetch.

The question is the following: 
1. Are you using following data-records ids from the deployment to get those or have you an alternative ?

**Comment by konstan** [comment]
```The data records ids fetched within this query are used in the deployment modal to associate them to the Deployment resource to allow him to know which data to fetch.```

Why this is required explicitly from the client? Why not to provide just a query to deployment resource when creating deployment, which would later materialise it into the list of ids (if needed; see below 2.). The referenced data-records/objects anyways are always internal to nuvla.

At the moment, in deployment I use the ids (from deployment `data-records` attribute) to get info about where the data is located (bucket / object name).

However, I see two options.

1. As a quick fix. Use `last=0` for displaying info on the cards. Use ids when card is selected for deployment.

2. I don't mind using just a query that could be persisted in the deployment (say `data-records-query`). So instead of thousands of GETs on IDs, I would issue PUT from my app (with pagination if needed). This PUT can contain required `select`s (for S3 object type this is usually `bucket` and `object` only).

I understand, that 1. creates a static set as apposed to 2. where the set is dynamic (someone can add data in between). In the case of GNSS the sets are always static by their nature. So, for now I would simply go for 2.: first, reduces the load and size of Nuvla side; second, reduces data mount operation time (less GETs, which is a considerable improvement when we are talking about >5K objects).

**Comment by 0xbase12** [comment]
> Why this is required explicitly from the client? Why not to provide just a query to deployment resource when creating deployment, which would later materialise it into the list of ids (if needed; see below 2.). The referenced data-records/objects anyways are always internal to nuvla.

Because it was first easy implementation idea. After that we kept it to not broke demos. 

I'm not opposed to changes there, but I don't want to break something in your code already deployed. 

So we can go for option 2 but it need changes on the API-SERVER and UI.

**Comment by konstan** [comment]
> I'm not opposed to changes there, but I don't want to break something in your code already deployed.

Great. The changes will be in one place only and it shouldn't be a big deal.

I suggest we discuss details/pros/cons, and then capture them in the ticket(s).

**Comment by konstan** [comment]
Fixed by https://github.com/nuvla/ui/pull/331/
Closing.
