### ISSUE TITLE
Environment variables are shuffled when the 9th one is added

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#376]
In an App, environment variables are shuffled when the 9th one is added.
And if I add more of them, they are added at a random position.

**Comment by schaubl** [comment]
Related to #361. 
Please see the comment in https://github.com/nuvla/ui/issues/361#issuecomment-632694416

**Comment by 0xbase12** [comment]
The issue is also present in urls, output-parameters, files and data binding sections
