### ISSUE TITLE
bad rendering on Safari

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#387]
https://github.com/nuvla/ui/blob/3e5142a52b129e8fa6e1f8d4eb81f32c3c4d1c23/code/src/cljs/sixsq/nuvla/ui/edge_detail/views.cljs#L471

on Safari, the ACLs button created a new row

**Comment by mebster** [comment]
Don't see the problem. Still there @cjdcordeiro?

**Comment by cjdcordeiro** [comment]
yep still there
![image](https://user-images.githubusercontent.com/4047767/90409680-c2c4e580-e0a9-11ea-80c8-4e9b429656ac.png)
