### ISSUE TITLE
add NB modal is missing white space between modal title and dynamic NB name 

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#410]
<img width="300" alt="Screen Shot 2020-07-29 at 1 08 05 PM" src="https://user-images.githubusercontent.com/4047767/88793155-a9acd100-d19c-11ea-8ec7-a82f4cc4bcb6.png">

**Comment by 0xbase12** [comment]
Fixed c219f39de2b11c68a975f8b12b0618e59ad106bd
