### ISSUE TITLE
refresh on deployment detail page refreshes the logs window making it impossible to analyse logs

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#414]
The global refresh on the page ignores the pause button in the logging section.

**Comment by MTrost** [comment]
How can I reproduce it?

**Comment by konstan** [comment]
* deploy an app that produces logs e.g., https://nuvla.io/ui/apps/examples/nginx
* on the Logs tab of the app's deployment page select the component to get logs for and then ask for logs
![Screenshot 2022-11-18 at 15 19 25](https://user-images.githubusercontent.com/353767/202725726-abd134c6-912d-4fc1-b2d5-bbd0e1199b18.png) 
* generate logs from the app (Nginx)
* go to the middle/top of the logs
* new logs are appended and the edit box is refreshed and scrolled down -- we want to avoid this.

Solution: append logs w/o scrolling.

**Comment by 0xbase12** [comment]
Fixed in https://github.com/nuvla/ui/blob/master/CHANGELOG.md#2332---2023-02-27
