### ISSUE TITLE
Subscriptions: allow to deploy when the state is "Past_due"

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#418]
Same should be done on api-server.

**Comment by 0xbase12** [comment]
@mebster Please confirm if you agree to deploy when subscription status is past_due ?

**Comment by mebster** [comment]
Yes for the moment as we get our payment status monitoring sorted, we'll remind our customers manually when payments are past due.

**Comment by 0xbase12** [comment]
implemented in api-server and ui
