### ISSUE TITLE
NuvlaBox location map should use inferred-location, unless location exists

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#430]
there's a new attribute in the nuvlabox-status resource, called `inferred-location`. This one is set by the NuvlaBox itself.

atm, the UI is only using the `location` attribute from the nuvlabox resource.

**Objective**: change the logic such that:

Option 1:
```
if `location` in `nuvlabox resource`:
  use it
elif `inferred-location` in `nuvlabox-status resource`:
  use this one instead
else:
  use nothing
```

Option 2:
 - show both `location` from nuvlabox and `inferred-location` from nuvlabox-status, with different pin colors, and the user can only control the `location` from nuvlabox

**Comment by mebster** [comment]
Fixed on the detailed page for a NB, but not on the list page.

**Comment by schaubl** [comment]
> Fixed on the detailed page for a NB, but not on the list page.

Done in #690
