### ISSUE TITLE
create workflow progress steps for complex operations, based on corresponding job progress

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#444]
![image](https://user-images.githubusercontent.com/4047767/95293260-63967c80-0873-11eb-9290-44b900034ddc.png)

Know that the job will go through N named steps (as a pipeline). Build the flow diagram with the named steps. Subscribe to (or query) the job events that start and end a step. Receive and process events. Update the progress bar accordingly.

In case of error in a step, provide:

 - error message,
 - (possibly) access to logs, and
 - access to recovery process.

**Comment by 0xbase12** [comment]
https://github.com/nuvla/api-server/issues/398

**Comment by 0xbase12** [comment]
#396

**Comment by 0xbase12** [comment]
#396
