### ISSUE TITLE
Allow to get a diff from 2 versions of a module (component or application)

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#472]
Top level issue: nuvla/nuvla#40

**Comment by cjdcordeiro** [comment]
please provide a diagram of the desired rendering

**Comment by mebster** [comment]
Does our text editor component support diffing text?  If so we could start with a simple diff of the versions as json.

**Comment by 0xbase12** [comment]
We use code-mirror:
Simple one git like - https://codemirror.net/mode/diff/index.html
Complex one which allow to merge lines: https://codemirror.net/demo/merge.html
