### ISSUE TITLE
create new tab "Deployments" in NB detail page

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#486]
since the NB resource doesn't have any direct reference to the corresponding IS and underlying deployments, a typical subscription for `nuvlabox-deployments` would imply querying ISG, ISs and Deployments on every page refresh (since the NB resource does not change upon deployment changes)

This seems too complex and inadequate for NBs with a lot of deployments. It would generate useless requests on every refresh.

Find a better way

**Comment by 0xbase12** [comment]
Fixed https://github.com/nuvla/ui/commit/9d746aa98e6f6fcd84baeef3bab9fc5a2356fdc3
