### ISSUE TITLE
add UI changes for supporting the "pull" and "mixed" provisioning mode operations

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#489]
this includes:
 - letting users choose how to launch their deployments (pull vs mixed mode)
 - same for NB actions
 - showing the deployment pages and NB details events page that a job is WAITING to be pulled and executed
 - show in the deployment page that the deployment is being monitoring by the IS, including the hearbeat (last monitoring info received)

**Comment by 0xbase12** [comment]
![image](https://user-images.githubusercontent.com/5518233/105710228-19670300-5f17-11eb-850f-c59ef4cbcf6e.png)

**Comment by 0xbase12** [comment]
As discussed on Slack, above is the lastest deployment dialog diagram. So in contrary to the first point, deployment is launched with execution-mode dictated by NB capability and credential check. User doesn't have the choice. @cjdcordeiro and @mebster do you confirm?

**Comment by cjdcordeiro** [comment]
confirmed

**Comment by 0xbase12** [comment]
In last diagram we considered only start action.

Deployment impacted actions are: start, update, stop

Questions?

1. Set deployment execution mode at start and use it for stop/update ? 
2. Or check credential/infra capabilities for each action every time?
3. If 2 is yes, what is execution-mode in deployment attribute for ?
4. What happens if credential check not finished and capabilities support pull => default value is mixed.
```
+---------------------+----------------+------------------+---------------------+
| IN: IS support Pull | IN: Cred check | OUT: Button text | OUT: Execution-mode |
+=====================+================+==================+=====================+
| NO                  | VALID          | Launch           | push                |
+---------------------+----------------+------------------+---------------------+
| NO                  | INVALID        | Force launch     | push                |
+---------------------+----------------+------------------+---------------------+
| No                  | UNKNOWN        | Force launch     | push                |
+---------------------+----------------+------------------+---------------------+
| No                  | In progress... | Force launch     | push                |
+---------------------+----------------+------------------+---------------------+
| Yes                 | VALID          | Launch           | mixed               |
+---------------------+----------------+------------------+---------------------+
| Yes                 | INVALID        | Force launch     | pull                |
+---------------------+----------------+------------------+---------------------+
| Yes                 | UNKNOWN        | Schedule         | pull                |
+---------------------+----------------+------------------+---------------------+
| Yes                 | In progress    | Force launch     | mixed               |
+---------------------+----------------+------------------+---------------------+
```

**Comment by cjdcordeiro** [comment]
1. is the easiest to implement for now, even though 2. could come as an improvement

3. if using 1., it is needed. if using 2., it comes as purely informative

4. agreed
