### ISSUE TITLE
broken link to "Full documentation at Nuvla Docs" on NB creation modal

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#505]
Page not found
https://docs.nuvla.io/docs/nuvlabox/nuvlabox-engine/quickstart.html

**Comment by konstan** [comment]
Now I see that the link is missing completely, but the `Full documentation at` text is present.

![Screenshot 2021-02-12 at 14 54 19](https://user-images.githubusercontent.com/353767/107776890-7568be80-6d42-11eb-902c-047c0dc1f932.png)

**Comment by 0xbase12** [comment]
I'm not able to reproduce. What is the version of the UI visible in the footer

**Comment by 0xbase12** [comment]
Closing

**Comment by konstan** [comment]
The problem was in my branch after merging from master - dictionary.cljs was missing `:nuvla-docs` key.
