### ISSUE TITLE
allow to individually enable/disable subscriptions through "manage" modal on subscription config

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#533]
![Screenshot 2021-02-17 at 08 51 59](https://user-images.githubusercontent.com/353767/108172695-6779bb80-70fd-11eb-9371-a9259f23d2f4.png)

**Comment by MTrost** [comment]
Currently subscription are only enabled/disabled globally for all resources:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/10104888/202990685-0134dea9-2f1e-48b8-8e8d-a5faebab4c0e.png">

Click on "manage" shows all resource subscriptions, but doesn't allow to enable/disable: 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/10104888/202990867-52bc7338-4dfd-4ca5-8744-4db97da81da0.png">

**Comment by konstan** [comment]
> Currently subscription are only enabled/disabled globally for all resources:

Yes, this should be the case now: users can only manage subscriptions as filters over resource types; no management of individual per-resource notifications is possible. Hence, this modal must be removed altogether along with the Subscriptions column. https://github.com/nuvla/ui/issues/997
