### ISSUE TITLE
allow editing of tags via detailed resource page

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#535]
Provide an easy way to edit tags via UI as a resource standard feature.

It's always possible via `/api` and then `raw`. But this is not the best way.

Here is the example of NB

![Screenshot 2021-02-17 at 09 14 59](https://user-images.githubusercontent.com/353767/108175118-a2c9b980-7100-11eb-9b21-78bb94c69d00.png)

Subscription to notifications configuration relies on tags for resource filtering.  Would be great to be able to add/remove the tags there.

**Comment by konstan** [comment]
... and in bulk?

**Comment by cjdcordeiro** [comment]
related to https://github.com/nuvlabox/agent/issues/48
