### ISSUE TITLE
deployment start/update modal: the launch/update button doesn't indicate it has been clicked

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#548]
After the click on the button, the creation of the job in the background can take some time.
After the click as been done, nothing show that the button has been clicked so it looks like if the click hasn't been made.
If we click again,  a new job will be created.

I think the button should be disabled until the operation (creation of the job) is completed.
Once the operation is completed, the modal disappear and we are redirected on the deployment page [already the case].
If the operation fail, the button can be reenabled.

**Comment by mebster** [comment]
This should be extended to all action confirmation button.  We can also add a spinner in the button, as is already in place for some.

**Comment by 0xbase12** [comment]
Done
