### ISSUE TITLE
Provide a more use friendly way to download the private ssh key

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#550]
Currently, we have to retrieve the private key from the events. And since it includes '\n' it cannot be saved directly in a file.  A download link or a copy to clipboard button would do a better job.

**Comment by mebster** [comment]
We already have this nice behaviour for add ssh key action on a NB

**Comment by mebster** [comment]
And another for when adding NuvlaBoxes.  We need to rationalise this.

**Comment by 0xbase12** [comment]
This is done and released
