### ISSUE TITLE
Update NuvlaBox should have progress follow up

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/ui#559]
After clicking on update a job is created but we have to go to api page to see the progress of the job.

Solutions:
a) Keep modal open and show job progress with an image of NB, a progress bar and show status message with lines returns if any
![image](https://user-images.githubusercontent.com/5518233/108828354-06535b80-75c7-11eb-9533-ab1798a8bd16.png)

b) When clicking on alert in notification bell menu, when an action is async (202 code) show a generic but less raw modal with progress bar and status message if any with an automatic refresh of job
<img width="908" alt="Screenshot 2021-02-23 at 11 06 10" src="https://user-images.githubusercontent.com/5518233/108828688-719d2d80-75c7-11eb-8292-5e90a79ec468.png">

**Comment by konstan** [comment]
There was one for generic progress of an action. From my notes:

![Screenshot 2021-02-23 at 11 14 29](https://user-images.githubusercontent.com/353767/108829647-b7a6c100-75c8-11eb-8fd9-c57318406c08.png)

**Comment by konstan** [comment]
Found https://github.com/nuvla/ui/issues/444

**Comment by mebster** [comment]
I don't think we should keep modals up to show progress. Modals should only be used for short specific tasks.  I also don't think the notification bell is the right place for progress display. Progress over multi-steps actions should be made generic in the UI.  For example, deployment or update of apps would also benefit from showing progress (e.g. number of replicas?)

We should find a consistent place to show progress of current actions in each detail page.  For example, status is shown in different places for NB and deployments:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/419519/108836347-06585900-75d1-11eb-8f17-60752ce2c37d.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/419519/108836409-16703880-75d1-11eb-9742-63d100900ff7.png">

A progress bar or steps (semantic ui) could be a simple starting point.

**Comment by mebster** [comment]
Done
