### ISSUE TITLE
variable substitution not fully supported on compose files

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#578]
reported by BSC:

> So, docker-compose allows you to specify ports using environment variables but docker-compose check in Nuvla apps fails and does not allow you to deploy (even if docker-compose supports it), for instance:
> ports:
> `"${DSJAVA_PORT:-2127}:${DSJAVA_PORT:-2127}"`
> Same happens with volumes that I want to specify via env. vars:
>   `${DATACLAY_INIT_VOLUME:-/opt/dataclay/shared}:/srv/dataclay/shared:rw`

**Comment by 0xbase12** [comment]
UI is calling `validate-docker-compose` action on the module. This action is implemented in job engine in following file https://github.com/nuvla/job-engine/blob/master/code/src/nuvla/job/actions/application_docker_compose_validate.py
