### ISSUE TITLE
keep the filters when browsing back from a deployment to Apps-Deployments tab

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#594]
To reproduce. On https://nuvla.io/ui/apps select the Deployments tab and provide a filter.

![Screenshot 2021-04-13 at 10 31 49](https://user-images.githubusercontent.com/353767/114522456-b0547900-9c43-11eb-8fe9-79009a984ac5.png)

Click on a deployment.

![Screenshot 2021-04-13 at 10 31 58](https://user-images.githubusercontent.com/353767/114522530-c06c5880-9c43-11eb-98bd-5263e847e36c.png)

And then go back to the Deployments tab

![Screenshot 2021-04-13 at 10 32 08](https://user-images.githubusercontent.com/353767/114522586-ccf0b100-9c43-11eb-90c4-5f949ba389f7.png)

The canned filter (STARTED) is lost and the free text search filter is no longer applied.

**Comment by MTrost** [comment]
This will be fixed by these 3 PRs:
1. Full text search: https://github.com/nuvla/ui/pull/1154
2. State filters: https://github.com/nuvla/ui/pull/1156
3. Additional filters wizard: https://github.com/nuvla/ui/pull/1160
