### ISSUE TITLE
on form validation error highlight section where the "the fields in red."

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#609]
Users are confused by 
```
Validation error!
The form is invalid. Please review the fields in red.
```
if they are not directed to the accordion with actual problematic fields.

<img width="1439" alt="Screenshot 2021-05-05 at 21 20 37" src="https://user-images.githubusercontent.com/353767/117197541-39e10c00-ade8-11eb-916c-080a06038969.png">

In this case, it turned out this was an issue with the missing license.

**Comment by mebster** [comment]
This should be fixed in the new tab layout, where the concerned tab turns red on validation error.

**Comment by konstan** [comment]
Great. Closing.
