### ISSUE TITLE
[bug] list of deployments disappears when one deployment changes state

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#621]
Steps to reproduce:
 1 - make sure you have one or more deployments in the https://nuvla.io/ui/apps deployments tab
 2 - launch a new deployment (or using an existing one which is in STARTED state)
 3 - stop a deployment

Result: for the rest of that refresh interval, the deployment cards will disappear

**Comment by MTrost** [comment]
fixed already
