### ISSUE TITLE
Add force terminate deployment

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#633]
This is required when the endpoint is gone, or the state machine is in a bad place.  This is a blunt instrument and must come with warnings.

Currently, the only way to terminate a "STOPPING" deployment is to manually change its status to "STOPPED", which is hidden and uncomfortable.

**Comment by 0xbase12** [comment]
I already implemented a force-delete action and a bulk-force-delete for deployment. On ui it's accessible via bulk actions menu.

**Comment by MTrost** [comment]
already implemented
