### ISSUE TITLE
only list the IS that are compatible with the type of app, at deployment time

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#653]
make user of the `compatibility` and `swarm_enabled` attributes to avoid cases where we are trying to deploy swarm apps into docker ISs

**Comment by mebster** [comment]
The solution here is to add a soft requirement that swarm should be enabled on a NB.  This means that the nominal behaviour of an NBE is that it supports both Docker and Swarm.  With this in place, we don't need to provide special logic regarding compatibility with swarm and Docker.

**Comment by cjdcordeiro** [comment]
what if the user sets SKIP_MINIMUM_REQUIREMENTS for the NB, or the NB leaves a cluster?
