### ISSUE TITLE
deployment bulk stop: "Select all" doesn't work

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#666]
If we use the button `Select all`, the query sent has the following data:
```json
{"filter": ""}
```
which give the following error:
```
Error bulk operation on :deployment (400)
Invalid CIMI filter. Parse error at line 1, column 2:
()
 ^
Expected one of:
"("
#"'[^'\\]*(?:\\.[^'\\]*)*'"
#"\"[^\"\\]*(?:\\.[^\"\\]*)*\""
#"([a-zA-Z][\w-]*[\w]+)|[a-zA-Z]"
#"\d+-\d+(-\d+)?(T\d+:\d+:\d+(\.\d+)?(Z|[+-]\d+:\d+))?"
#"\d+"
"null"
"false"
"true"
```

Without a filter, the following result is returned:
```Bulk request should contain a non empty cimi filter.```

With a filter like `id!=null` or `id^=''` it works.

**Comment by 0xbase12** [comment]
Fixed 382a47cc8ff5e08eb021c1f1645b273bdef2ff01
