### ISSUE TITLE
clicking on Deployments in Dashboard brings to Apps

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#674]
I was given a deployment ID and wanted to find it. From the Dashboard page clicked on Deployments

![Screenshot 2021-08-04 at 14 06 35](https://user-images.githubusercontent.com/353767/128177908-9e88a3b5-8b29-4c45-a306-4281106f6e48.png)

but ended up on Apps page.

![Screenshot 2021-08-04 at 14 09 53](https://user-images.githubusercontent.com/353767/128178265-2dccc09b-f874-4e3d-847a-5a73c0b796e5.png)

Well... then, of course, realized that I'm on the Deployment tab of the Apps. This is a bit confusing.

Also, having the deployment ID - how can I find the deployment from the Apps/Deployments page? It was possible to slap the ID in the URL when it was `ui/deployment/` but now it's `ui/apps/` so this doesn't work anymore.

**Comment by mebster** [comment]
With a deployment ID, you can still add it to /ui/deployment/<ID>

**Comment by mebster** [comment]
as for the "confusion", do you have a suggestion?
