### ISSUE TITLE
grey out or remove "bin bucket" pictogram from deployment card after confirming deletion

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#70]
The same way it's done for the "cross" on the card on the deployment termination. Otherwise, "bins" stay there on the cards until the page auto-refreshes and the cards disappear. It's a bit confusing. This is a cosmetic thing.

**Comment by 0xbase12** [comment]
Fixed in this commit https://github.com/nuvla/ui/commit/8afd6b817e186048dd1152a1fa298d41fc7423ba
