### ISSUE TITLE
As User, on Data records tab of Data page, I can select individual data-records and request processing

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#711]
Deployment receives the list of the selected assets.

**Comment by 0xbase12** [comment]
Data-record can be a data-object or a pointer to FTP location or other storage services.

Deployment modal should show only the infrastructure-service that the data-record is on?

Should we filter list of applications to only application accepting content-type equal to the one defined in the data-record? Or we let user select any application?

**Comment by konstan** [comment]
@0xbase12 

> Deployment modal should show only the infrastructure-service that the data-record is on?

Yes.

> Should we filter list of applications to only application accepting content-type equal to the one defined in the data-record?

Yes. If the content-type is the same on all the data-records selected. Otherwise, propose the list of all apps user can see.
