### ISSUE TITLE
maps are not showing on Nuvla installed from scratch

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#724]
![Screenshot 2021-11-19 at 13 40 01](https://user-images.githubusercontent.com/353767/142624551-ad2922cb-eee9-45f1-bbd8-0fc24063da99.png)

**Comment by 0xbase12** [comment]
You need to create an account on mapbox. Create an access-token and configure it into ui-config file variable `mapbox-access-token`.

**Comment by konstan** [comment]
Opened documentation related issue https://github.com/nuvla/deployment/issues/74.
Closing.
