### ISSUE TITLE
by default put user to the list of the users that can be added to the group

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#728]
User who created the group is not in the list of potential group members:
![Screenshot 2021-11-23 at 08 50 55](https://user-images.githubusercontent.com/353767/142988304-3956b1d6-b3dd-4345-bb63-a7589dfa8f9e.png)

Users can always see themselves. Hence, they by default can be added (with a proper handle) to the dropdown list of the users that can be added to the group the user manages. ATM, user needs to 
1. switch to the Details tab
2. copy the full ID (see https://github.com/nuvla/ui/issues/727)
3. return back to the Groups tab
4. paste the ID to the edit box of the dropdown

And this also assumes that the user knows all that.

**Comment by 0xbase12** [comment]
I created a group, and I was able to add myself from the dropdown to the group.

**Comment by 0xbase12** [comment]
Demo of the issue has been provided. In some cases dropdown list is empty.
