### ISSUE TITLE
add support for URL redirection when session expires

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/ui#730]
**Currently**
given the url https://nuvla.io/ui/apps/sixsq/blackbox, if the user does not have a valid session, the UI will redirect the user to the login page, and then to the welcome page, always

**Proposed solution**
The target url should be kept, even when login is required, so that the user is redirected to the intended page after the login

**Comment by 0xbase12** [comment]
This is also useful to redirect user to profile page to add a payment method
Related to https://github.com/SixSq/tasklist/issues/2017

**Comment by 0xbase12** [comment]
Allow also url redirection like this one when the page is not protected https://nuvla.io/ui/sign-in?redirect=profile
