### ISSUE TITLE
on the calendars on the Data page allow to select dates in the future

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#761]
EO data has PLANNED asset type with all the metadata pre-defined (including geometry).

**Comment by MTrost** [comment]
@konstan 

For From and To fields?

<img width="918" alt="image" src="https://user-images.githubusercontent.com/10104888/203099647-58d027b3-a2fb-440a-bb25-d6d1d1891e51.png">

**Comment by konstan** [comment]
Just finding the reasoning to close this one. The Data page is mostly to request processing of the existing data. Even if the meta-data catalogue contains data records with the dates in the future, anyways it will not be possible to process the data. It was added just to show the Earth Observation planned data for UbiSAP. We may get back to this with GSTP, but not for now. Closing.
