### ISSUE TITLE
NuvlaBox page: action bar doesn't display actions if browser window is too small

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#771]
![Screenshot 2022-01-17 at 19 24 42](https://user-images.githubusercontent.com/2462866/149821664-dbb03b5f-6f14-4c27-bf63-f73f9478a792.png)
![Screenshot 2022-01-17 at 19 24 57](https://user-images.githubusercontent.com/2462866/149821665-63b83ef9-fb23-4ecd-ae8f-197031580048.png)

**Comment by 0xbase12** [comment]
Same issue is visible in cimi-detail page
