### ISSUE TITLE
Host-level management is broken in Nuvlabox creation modal

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/ui#793]
Clipboard content is broken. User get following string when he click on copy icon: [object Object]
Popup is empty.

<img width="1440" alt="Screenshot 2022-02-14 at 16 05 15" src="https://user-images.githubusercontent.com/5518233/153889339-38fa9550-5f32-44bf-9f6a-ee7668e23b9a.png">

**Comment by MTrost** [comment]
Fixed by https://github.com/nuvla/ui/pull/904
