### ISSUE TITLE
Rename NuvlaBox to Edge and Infrastructure to Cloud

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/ui#821]
Related to https://github.com/SixSq/tasklist/issues/1977

**Comment by 0xbase12** [comment]
### Questions if we should rename

Add NB modal:
- [ ] File `nuvlabox-engine.zip`
- [ ] command line: `docker-compose -p nuvlabox ...`
- [ ] NuvlaDocs link broken and point to Nuvlabox page. Will it be renamed?

**Comment by FabianMk** [comment]
https://github.com/nuvla/ui/pull/822
