### ISSUE TITLE
Display infrastructure/service group in Edge detail page

### ISSUE THREAD

**Issue by FabianMk** [nuvla/ui#823]
As a user with a NE I need to see my attached services/infrastructure group in the NE detail page so that I can see them.

**Comment by 0xbase12** [comment]
@konstan @mebster Here is the result of moving services to NuvlaEdge detail page. 

How should we name this `services` section. Should we show this section when there is only one infrastructure-service.
Usually when there is one it's a `swarm` or `kubernetes` infra-service. It can give an idea of what's available in the NuvlaEdge device.

![Screenshot 2022-05-05 at 09 11 15](https://user-images.githubusercontent.com/5518233/166877120-7a8d89cd-786d-4570-b190-f0c04304e171.png)

**Comment by konstan** [comment]
`Services` LGTM. If there was a way to have a tooltip - I would write: Services running on the edge device (e.g., Docker, Kubernetes, S3).

Just a note. I see the Deployments card has a pictogram, but others don't.

**Comment by mebster** [comment]
"Infrastructure Services" for me is more precise. This is to be clear compared to other types of services, such as the data-gateway and the agent that are also referred to as services in our documentation.  You could use a cloud icon if you wanted one, perhaps.

**Comment by 0xbase12** [comment]
Thanks, this answer one question. We didn't get answer for the following question:

Should we display Infrastructure Services section when there is only one in the list (basically the swarm or kubernetes) ?

**Comment by mebster** [comment]
Sorry.  I agree with your suggestion that even one service is useful, if only to show which CoE is installed.  So Yes!

**Comment by 0xbase12** [comment]
Implemented 94cbcf1922bdc1b43801ac6974eff82be6a255ba
