### ISSUE TITLE
Link to deployment on edge page goes to events tab

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#826]
instead of deployment tab 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/419519/168093252-2e8460d0-c5de-4880-a33f-c41118ef62a0.png">

**Comment by 0xbase12** [comment]
This bug was introduced when we added the logs tab. The pointer index changed and caused this issue. 
It's not the first time this bug happened. We should not use indexes for tab navigation but keywords. We will fix the bug for now but a refactor is needed to avoid such issue.

**Comment by mebster** [comment]
Indeed

**Comment by 0xbase12** [comment]
Fixed
