### ISSUE TITLE
when deployment is stopped remove the URL link to the app

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#837]
When the deployment is topped, the link to the app is removed from the card

![Screenshot 2022-06-01 at 17 18 52](https://user-images.githubusercontent.com/353767/171439889-c473de7e-d86d-40e5-bcd1-26d5124bfca0.png)

But it's still available on the details page (green **datalab** one)

![Screenshot 2022-06-01 at 17 18 31](https://user-images.githubusercontent.com/353767/171439774-6b87ead7-c288-42c9-8114-b7263b87e31d.png)

The same applies to the URL tab.

![Screenshot 2022-06-01 at 17 22 03](https://user-images.githubusercontent.com/353767/171440517-ad77c9cc-d585-46ca-88b9-7b2a29b8fd02.png)

**Comment by 0xbase12** [comment]
Agree to hide it from summary section.
I think it's useful to keep url tab with the links even if stopped. This can help to see what was the urls. 

What about keeping the urls but make them non clickable.
