### ISSUE TITLE
id of Project doesn't correspond to the link behind it

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#839]
For example, on `Example` project the id is set to `2abe-9fbb-40ba-8656-439806253c78` while the link points to https://nuvla.io/ui/api/module/19422abe-9fbb-40ba-8656-439806253c78

![Screenshot 2022-06-02 at 16 42 24](https://user-images.githubusercontent.com/353767/171656462-60f0ba03-8be4-4e9e-82e7-ce68823ddef5.png)

**Comment by FabianMk** [comment]
<img width="606" alt="Screenshot 2022-06-07 at 11 50 07" src="https://user-images.githubusercontent.com/8279995/172338534-04b1d2ff-f705-42e2-8033-4d56abf0d306.png">

**Comment by FabianMk** [comment]
<img width="593" alt="Screenshot 2022-06-07 at 11 51 38" src="https://user-images.githubusercontent.com/8279995/172338843-ae54ce81-ef22-4138-9075-0f6a7a1fec1b.png">

**Comment by FabianMk** [comment]
@mebster @konstan @0xbase12 I suggest we show the `module/` since it is part of the id.

**Comment by konstan** [comment]
@FabianMk I would rather not show `module/` as this adds an extra entity into the picture of projects and applications. "Module" is our internal implementation detail where we can have modules of different types. I'd rather not expose it to the user.

At the same time, the issue is about the consistency in the ID which is shown on the card and the actual link to the module behind it.  Please check on your side which module will you get to and if it matches the one ID shown on the card.

**Comment by FabianMk** [comment]
https://github.com/nuvla/ui/pull/840
