### ISSUE TITLE
"create user" fails with "Oops :(. An error occured. Please contact the system administrator."

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#86]
![Screenshot 2019-05-29 at 09 14 39](https://user-images.githubusercontent.com/353767/58537043-5171ec00-81f2-11e9-9603-0fdfbcd4816e.png)

And this should probably be "invite" instead of "create".

**Comment by konstan** [comment]
I the case above asked to "create" a user which already existed in the system. However, other users when inviting others will not know for sure. So it's better to respond with `user "a@b.c" already exists`.

**Comment by 0xbase12** [comment]
Server side issue. The response is a status code 409 Conflict with no message. The same result is visible when you sign-up with the same email another time

**Comment by 0xbase12** [comment]
https://github.com/nuvla/api-server/issues/188
