### ISSUE TITLE
Rethink naming between "host level management" and "playbook"

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#874]
It's hard for a user to associate the action "Enable host level management" with the "Playbook" feature.

The emergency feature mentions playbook, which its better.

**Comment by MTrost** [comment]
Image from [duplicate issue](https://github.com/nuvla/ui/issues/872) 
![image](https://user-images.githubusercontent.com/10104888/202510305-192a5141-302c-487e-8db5-062e769617d1.png)
