### ISSUE TITLE
Sign up failed and succeeded at the same time.

### ISSUE THREAD

**Issue by schaubl** [nuvla/ui#89]
Sign up failed and succeeded at the same time.
<img width="544" alt="Screenshot 2019-05-29 at 10 04 27" src="https://user-images.githubusercontent.com/2462866/58540261-48384d80-81f9-11e9-8bc2-95e4bb6591cf.png">

**Comment by 0xbase12** [comment]
Fixed in this commit 975842e3f22b2d6c4f4898a57c71edba8c561a7c
