### ISSUE TITLE
Subscription notifications UI improvements

### ISSUE THREAD

**Issue by MTrost** [nuvla/ui#912]
#### "Disk usage %"
<img width="649" alt="image" src="https://user-images.githubusercontent.com/10104888/193260141-9c5f8539-4649-41a5-b528-6b48840e3aac.png">

Additional information if a wide filter is used and another disk is selected: Selected disk may not be available on all resources (same for Rx/Tx).

Is it a text input or do we give them a Dropdown with all possible options?
(same question for Rx/Tx)

#### "Network Rx/Tx GB"
<img width="649" alt="image" src="https://user-images.githubusercontent.com/10104888/193260063-17fe6f78-9d42-4e40-83ec-1b0e644a51c9.png">

#### NuvlaEdge online

I propose a short info text: "Get notified when NuvleEdge changes status changes to offline or online."

**Comment by 0xbase12** [comment]
I suppose that input fields will appear or be enabled when option is selected (e.g. Custom in days).

Custom [Input field][label days]

Perhaps `Specify network interface` is better than `Use other network?`.  Same thing for disk.

Other than that LGTM. Liked the sketch to show how it will look like.

**Comment by MTrost** [comment]
> I suppose that input fields will appear or be enabled when option is selected (e.g. Custom in days).
>
> Custom [Input field][label days]
Yes, that's the plan!

> Perhaps Specify network interface is better than Use other network?. Same thing for disk.
Thanks, that's way better: I didn't know what to call it, that's why I put the question mark at the end (not very obvious...).

Thanks for feedback!

I edited at the same time you were answering so I ask here again. 
The input field for disk and network interface: Should this be a free text field or a dropdown with all possible options (if that is even reasonably feasible).

**Comment by 0xbase12** [comment]
free text field for interfaces since network interfaces can be an id like we saw with konstan

**Comment by konstan** [comment]
Re the messages.

**"Disk usage %"**
```
Observes the primary partition.
```
Also, ATM collection of the per disk/partition metrics and their naming is not fully working on NE (just checked with @ignacio-penas). So, showing the row with "Specify disk name" doesn't make sense at the moment.

**"Network Rx/Tx GB"**
```
Default will observe the traffic on the default gateway on monthly basis (resets on the 1st of the month).
```

**Comment by MTrost** [comment]
@konstan or @0xbase12 : Can one of you provide me with the French translations for
- Observes the primary partition.
- Default will observe the traffic on the default gateway on monthly basis (resets on the 1st of the month).

**Comment by 0xbase12** [comment]
> @konstan or @0xbase12 : Can one of you provide me with the French translations for
> 
>     * Observes the primary partition.
> 
>     * Default will observe the traffic on the default gateway on monthly basis (resets on the 1st of the month).

- Surveille la partition principale.
- Surveille le trafic sur la passerelle par défaut sur une base mensuelle (se réinitialise chaque 1er du mois).

Observes is it better to replace it with monitor? 
Too much default in the second sentence. We remove the first one?
