### ISSUE TITLE
Edges: do not display N.x.x as version on the table view

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#955]
This is shown when the NE is in a New state with no physical NE behind yet. Showing a version number is confusing. 

<img width="1284" alt="Screenshot 2022-11-08 at 14 00 52" src="https://user-images.githubusercontent.com/353767/200571834-ceab13f5-11f8-46da-8139-283f7a249ac3.png">

The actual deployed NE version will be sent by the Agent after commissioning.

**Comment by konstan** [comment]
It was indeed confusing to me. Because the table doesn't show the **state** the NEs are in - I at the beginning was under an impression that NEs were sending 2.x.x to Nuvla. Hence, two things.

First, it looks like there is a bug with displaying the pictograms

![Screenshot 2022-11-11 at 10 29 39](https://user-images.githubusercontent.com/353767/201310253-3506a48f-e440-475b-a122-49b74f51047f.png)

I suggest, if pictogram can not be displayed - desplay as default the value of the state instead (NEW, etc). Also, when hoowering over pictograms - dispaly the state value as well (hepls ppl to get used to the mapping).

Second, a really picky comment... I would display 2.x.y (or 2.y.z), because minor and patch are independend vars. 

As a side note. For the major, I agree that the value taken from **version** on NE resource is a good approxiamtion of what the NE's major version number will be (as we agreed that the each backward incompatible schema change results in the major version bump).

**Comment by MTrost** [comment]
> Second, a really picky comment... I would display 2.x.y (or 2.y.z), because minor and patch are independend vars.

I like that, don't think it's picky! 👍

**Comment by konstan** [comment]
I opened #960 on icons not displayed in the table view on the Edge page.

**Comment by konstan** [comment]
@MTrost I opened https://github.com/nuvla/ui/issues/962 to track the 2.x.x -> 2.y.z. I'm closing this one as we now have separate issues per the topics discussed here.
