### ISSUE TITLE
Deployments: date selection in logs tab is skewed - v2.32.9

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#992]
![Screenshot 2022-11-18 at 14 29 05](https://user-images.githubusercontent.com/353767/202716528-9f069400-9019-4e8d-80c1-efe1c4445add.png)

**Comment by MTrost** [comment]
@konstan not on my machine:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/10104888/202744619-7b975b9d-801b-4f75-8640-63621e3db16b.png">


What browser and window width?

**Comment by konstan** [comment]
Chrome and anything wide than this renders it badly

![Screenshot 2022-11-18 at 16 48 21](https://user-images.githubusercontent.com/353767/202745346-d1d990fd-fda4-4396-8c5a-36cb2a15b32c.png)

**Comment by konstan** [comment]
![Screen-Recording-2022-11-18-at-16 50 40](https://user-images.githubusercontent.com/353767/202746354-4bc3c98e-a87c-4f15-b2b5-bf79126e275f.gif)

**Comment by MTrost** [comment]
Thanks, can reproduce now on production

**Comment by MTrost** [comment]
Datepicker as direct child of ui/MenuItem is broken, had to move it into a new div
